name: Build and Test # the name of the workflow
on: #[ push ] # the triggers. This is just when there's a push
  workflow_call: # change to more of a function. 
    inputs: # args
      upload-pages-artifact: # arg name
        type: boolean 
        required: false # not required, could also provide a default: true, but it defaults to false
jobs: # The list of jobs to run
  build-and-test: # name of our job
    runs-on: ubuntu-latest # specify the runner
    steps: # list of the steps
      - uses: actions/checkout@v3 # brings our code into the current directory
      - uses: actions/setup-node@v3 # installs node.js
        with: # the inputs into the previous step. 
          node-version: 18
      - run: npm ci # clean install. 
      - run: npm run build # build the project
      - run: npm run test:integration # run the integration tests
      - run: npm run test:e2e # run the e2e tests
      - uses: actions/upload-artifact@v3 # allows us to save our cypress videos
        with: 
          name: e2e-videos # name of the artifact
          path: cypress/videos/ # directory to save artifacts from in the runner environment
      - if: ${{ inputs.upload-pages-artifact }}
        uses: actions/upload-pages-artifact@v1 # upload the build to github pages if deploy
        with:
          path: build/
